BootCamp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dev.urls'))
]

dev/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'^register$', views.AddUser.as_view(), name='add-user'),
    url(r'^login$', views.UserLogin.as_view(), name='login-user'),
    url(r'^addproject$', views.AddProject.as_view(), name='add-project'),
    url(r'^logout$', views.logout_user, name='logout'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.ProjectDelete.as_view(), name='project-delete'),
    url(r'^(?P<pk>[0-9]+)$', views.ViewUser.as_view(), name='user-detail')
]

dev/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    github_link = models.CharField(max_length=1000)

    def __str__(self):
        return self.title + ' - ' + self.creator.username

dev/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Project


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'username', 'password']


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ['username', 'password']


class AddProjectForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    github_link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Project
        fields = ['title', 'description', 'github_link']

dev/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views import generic
from .models import Project
from forms import UserRegisterForm, UserLoginForm, AddProjectForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect


class IndexView(generic.ListView):
    template_name = 'dev/index.html'
    context_object_name = 'projects'
    paginate_by = 5

    def get_queryset(self):
        return Project.objects.get_queryset().order_by('-id')


class AddUser(generic.View):
    form_class = UserRegisterForm
    template_name = 'dev/register-form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.username = username
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
        return redirect('home')


class UserLogin(generic.View):
    form_class = UserLoginForm
    template_name = 'dev/login-form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home')


class AddProject(generic.CreateView):
    form_class = AddProjectForm
    template_name = 'dev/add-project.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return super(AddProject, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('home')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super(AddProject, self).form_valid(form)


def logout_user(request):
    logout(request)
    return redirect('/')


class ViewUser(generic.DetailView):
    model = User
    template_name = 'dev/UserDetail.html'
    context_object_name = 'user'


class ProjectDelete(generic.DeleteView):
    model = Project
    success_url = reverse_lazy('home')

dev/templates/dev/UserDetail.html
{% extends 'dev/base_template.html' %}
{% block title %}Account{% endblock %}
{% block body %}

    <div class="jumbotron">
        <div class="container text-center">
            <h1>{{ user.username }}</h1>
            <p>Some text that represents "Me"...</p>
        </div>
    </div>

    <div class="container-fluid bg-3 text-center">
        <h2>CONTRIBUTIONS</h2><br>
        {% for project in user.project_set.all %}
            <div class="w3-card-4" style="margin: 5%">
                <header class="w3-container w3-light-grey">
                    <h3>{{ project.title }}{% if request.user == user %}
                        <form action="{% url 'project-delete' project.id %}" method="post" style="display: inline">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ project.id }}">
                            <button type="submit" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"></span> </button>
                        </form>
                    {% endif %}</h3>
                </header>
                <div class="w3-container">
                    <p>{{ project.description }}</p>
                </div>
                <button  class="w3-button w3-block w3-dark-grey" onclick="window.location.href='{{ project.github_link }}'" >Contribute/View Source Code</button>
            </div>
        {% endfor %}
    </div><br><br>

    <footer class="container-fluid text-center">
        <p>Contact me at <a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
    </footer>
{% endblock %}

dev/templates/dev/add-project.html
{% extends 'dev/base_template.html' %}
{% block title %}Add a new Project{% endblock %}
{% block add-project %}class="active"{% endblock %}
{% block body %}
    <div class ="center-container">
    <form action="" method="post" style="margin: auto">

        {% csrf_token %}
    <ul class = "list-group" style="border-width: 10px">

        {% for field in form %}
            <div class="form-group">
            <li class="list-group-item" >
            <label>{{ field.label_tag }}</label><br>
            <div style="width: inherit">{{ field }}</div>
            </li>
            </div>
        {% endfor %}

    <li class="list-group-item"><button type="submit" class="btn btn-default form-control">Submit</button></li>
    </ul>
    </form>
    </div>
{% endblock %}

dev/templates/dev/base_template.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <style>
        *{
            transition: 0.3s
        }
        .navbar-brand{
            font-family: 'Kaushan Script';
        }
        .center-container {
            min-height: 100%; /* Fallback for browsers do NOT support vh unit */
            min-height: 100vh; /* These two lines are counted as one :-)       */
            display: flex;
            align-items: center;
        }

    </style>
</head>
<body style="padding: 10px">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">BootCamp</a>
        </div>
        <ul class="nav navbar-nav">
            <li {% block home %}{% endblock %}><a href="{% url 'home' %}">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li {% block add-project %}{% endblock %}><a href="{% url 'add-project' %}"><span class="glyphicon glyphicon-pencil"></span>Add a project</a>
                <li><a href="{% url 'user-detail' request.user.id %}"><span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a></li>
                <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            {% else %}
                <li {% block signup %}{% endblock %}><a href="{% url 'add-user' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li {% block login %}{% endblock %}><a href="{% url 'login-user' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% endif %}
        </ul>

    </div>
</nav>

<div class="container" style="margin-top:50px">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

dev/templates/dev/index.html
{% extends 'dev/base_template.html' %}
{% block title %}Home{% endblock %}
{% block home %}class="active"{% endblock %}
{% block body %}
    {% for project in projects %}
        <div class="w3-card-4" style="margin: 3%">
            <header class="w3-container w3-light-grey">
                <h3>By {{ project.creator.username }}</h3>
            </header>
            <div class="w3-container">
                <h2>{{ project.title }}</h2>
                <hr>
                <p>{{ project.description }}</p>
            </div>
            <button  class="w3-button w3-block w3-dark-grey" onclick="window.location.href='{{ project.github_link }}'" >Contribute/View Source Code</button>
        </div>
    {% endfor %}
    {% if is_paginated %}

        <ol class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ol>
    {% endif %}
{% endblock %}

dev/templates/dev/login-form.html
{% extends 'dev/base_template.html' %}
{% block title %}Login{% endblock %}
{% block login %}class="active"{% endblock %}
{% block body %}
    <div class ="center-container">
    <form action="" method="post" style="margin: auto">

        {% csrf_token %}
    <ul class = "list-group" style="border-width: 10px">

        {% for field in form %}
            <div class="form-group">
            <li class="list-group-item">
            <label>{{ field.label_tag }}</label><br>
            {{ field }}
            </li>
            </div>
        {% endfor %}

    <li class="list-group-item"><button type="submit" class="btn btn-default form-control">Submit</button></li>
    </ul>
    </form>
    </div>
{% endblock %}

dev/templates/dev/register-form.html
{% extends 'dev/base_template.html' %}
{% block title %}Sign-up{% endblock %}
{% block signup %}class="active"{% endblock %}
{% block body %}
    <div class ="center-container">
        <form action="" method="post" style="margin: auto">

            {% csrf_token %}
            <ul class = "list-group" style="border-width: 10px">

                {% for field in form %}
                    <div class="form-group">
                        <li class="list-group-item">
                            <label>{{ field.label_tag }}</label><br>
                            {{ field }}
                        </li>
                    </div>
                {% endfor %}

                <li class="list-group-item"><button type="submit" class="btn btn-default form-control">Submit</button></li>
            </ul>
        </form>
    </div>
{% endblock %}